### ISSUE TITLE
mismatched parentheses 

### ISSUE THREAD

**Issue by akoaysigod** [swift-emacs/swift-mode#35] opened 2014-10-03 15:10 UTC
I keep getting this error only when using swift mode. I opened up a fresh install of emacs and only installed swift-mode and I get the same problem. This happens after the class declaration. Basically, I can create a class without issues but as soon as I finish typing func I get the warning and indentation, etc. stops working correctly.

**Comment by olepor** [comment] 2015-06-16 13:50
Anyone made any progress on this issue yet?

**Comment by akoaysigod** [comment] 2015-06-16 14:29
@olepor as far as the warning goes it's still happening. I haven't had the problem with the indentation in a while though.

**Comment by olepor** [comment] 2015-06-17 09:14
I seem to have a problem with autopairing braces in swift-mode. Anyone else recognise these symptoms? Parenthesis work just fine, but there is something that messes with the mathcing of braces. It seems like it is trying to match them (the braces) with keywords- such as if, for... etc
instead of the mathcing brace. I guess this has something to do with the swift-mode functionality. 
@akoaysigod

**Comment by ap4y** [comment] 2015-06-17 21:07
Hey @olepor can you make a gist or something with an example of the situation (something minimal). I assume the problem is the error message (`Mismatched parenthesis`), right? Or you have a different problem?

**Comment by TheB3arGod** [comment] 2016-07-01 19:11
Hi

I am having this problem as well.  It seems the '..<' and related range syntax are causing the issue.  The standard '...' range works perfectly fine, however when the the angle brackets are introduced it begins to complain about mismatching parenthesis.

I am using Emacs 24.5.1 with swift-mode installed through the MELPA repository.

Thank you for your continued support.

**Comment by taku0** [comment] 2016-09-18 13:14
Closing in favor of the new indentation logic.

**Closed by taku0** 2016-09-18 13:14 UTC
Labels: bug
